/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.api;

import io.oferto.argo.client.api.ArtifactServiceApi;
import io.oferto.argo.client.model.GrpcGatewayRuntimeError;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ArtifactServiceApi
 */
@Ignore
public class ArtifactServiceApiTest {

    private final ArtifactServiceApi api = new ArtifactServiceApi();

    
    /**
     * Get an artifact.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void artifactServiceGetArtifactFileTest() throws Exception {
        String namespace = null;
        String idDiscriminator = null;
        String id = null;
        String nodeId = null;
        String artifactName = null;
        String artifactDiscriminator = null;
        byte[] response = api.artifactServiceGetArtifactFile(namespace, idDiscriminator, id, nodeId, artifactName, artifactDiscriminator);

        // TODO: test validations
    }
    
    /**
     * Get an input artifact.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void artifactServiceGetInputArtifactTest() throws Exception {
        String namespace = null;
        String name = null;
        String nodeId = null;
        String artifactName = null;
        byte[] response = api.artifactServiceGetInputArtifact(namespace, name, nodeId, artifactName);

        // TODO: test validations
    }
    
    /**
     * Get an input artifact by UID.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void artifactServiceGetInputArtifactByUIDTest() throws Exception {
        String uid = null;
        String nodeId = null;
        String artifactName = null;
        byte[] response = api.artifactServiceGetInputArtifactByUID(uid, nodeId, artifactName);

        // TODO: test validations
    }
    
    /**
     * Get an output artifact.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void artifactServiceGetOutputArtifactTest() throws Exception {
        String namespace = null;
        String name = null;
        String nodeId = null;
        String artifactName = null;
        byte[] response = api.artifactServiceGetOutputArtifact(namespace, name, nodeId, artifactName);

        // TODO: test validations
    }
    
    /**
     * Get an output artifact by UID.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void artifactServiceGetOutputArtifactByUIDTest() throws Exception {
        String uid = null;
        String nodeId = null;
        String artifactName = null;
        byte[] response = api.artifactServiceGetOutputArtifactByUID(uid, nodeId, artifactName);

        // TODO: test validations
    }
    
}
