/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.api;

import io.oferto.argo.client.api.ClusterWorkflowTemplateServiceApi;
import io.oferto.argo.client.model.GrpcGatewayRuntimeError;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplate;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateDeleteResponse;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateLintRequest;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateList;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateUpdateRequest;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClusterWorkflowTemplateServiceApi
 */
@Ignore
public class ClusterWorkflowTemplateServiceApiTest {

    private final ClusterWorkflowTemplateServiceApi api = new ClusterWorkflowTemplateServiceApi();

    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void clusterWorkflowTemplateServiceCreateClusterWorkflowTemplateTest() throws Exception {
        IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateCreateRequest body = null;
        IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplate response = api.clusterWorkflowTemplateServiceCreateClusterWorkflowTemplate(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void clusterWorkflowTemplateServiceDeleteClusterWorkflowTemplateTest() throws Exception {
        String name = null;
        String deleteOptionsGracePeriodSeconds = null;
        String deleteOptionsPreconditionsUid = null;
        String deleteOptionsPreconditionsResourceVersion = null;
        Boolean deleteOptionsOrphanDependents = null;
        String deleteOptionsPropagationPolicy = null;
        List<String> deleteOptionsDryRun = null;
        IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateDeleteResponse response = api.clusterWorkflowTemplateServiceDeleteClusterWorkflowTemplate(name, deleteOptionsGracePeriodSeconds, deleteOptionsPreconditionsUid, deleteOptionsPreconditionsResourceVersion, deleteOptionsOrphanDependents, deleteOptionsPropagationPolicy, deleteOptionsDryRun);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void clusterWorkflowTemplateServiceGetClusterWorkflowTemplateTest() throws Exception {
        String name = null;
        String getOptionsResourceVersion = null;
        IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplate response = api.clusterWorkflowTemplateServiceGetClusterWorkflowTemplate(name, getOptionsResourceVersion);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void clusterWorkflowTemplateServiceLintClusterWorkflowTemplateTest() throws Exception {
        IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateLintRequest body = null;
        IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplate response = api.clusterWorkflowTemplateServiceLintClusterWorkflowTemplate(body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void clusterWorkflowTemplateServiceListClusterWorkflowTemplatesTest() throws Exception {
        String listOptionsLabelSelector = null;
        String listOptionsFieldSelector = null;
        Boolean listOptionsWatch = null;
        Boolean listOptionsAllowWatchBookmarks = null;
        String listOptionsResourceVersion = null;
        String listOptionsResourceVersionMatch = null;
        String listOptionsTimeoutSeconds = null;
        String listOptionsLimit = null;
        String listOptionsContinue = null;
        IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateList response = api.clusterWorkflowTemplateServiceListClusterWorkflowTemplates(listOptionsLabelSelector, listOptionsFieldSelector, listOptionsWatch, listOptionsAllowWatchBookmarks, listOptionsResourceVersion, listOptionsResourceVersionMatch, listOptionsTimeoutSeconds, listOptionsLimit, listOptionsContinue);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void clusterWorkflowTemplateServiceUpdateClusterWorkflowTemplateTest() throws Exception {
        String name = null;
        IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateUpdateRequest body = null;
        IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplate response = api.clusterWorkflowTemplateServiceUpdateClusterWorkflowTemplate(name, body);

        // TODO: test validations
    }
    
}
