/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.api;

import io.oferto.argo.client.api.SensorServiceApi;
import io.oferto.argo.client.model.GrpcGatewayRuntimeError;
import io.oferto.argo.client.model.IoArgoprojEventsV1alpha1Sensor;
import io.oferto.argo.client.model.IoArgoprojEventsV1alpha1SensorList;
import io.oferto.argo.client.model.SensorCreateSensorRequest;
import io.oferto.argo.client.model.SensorDeleteSensorResponse;
import io.oferto.argo.client.model.SensorUpdateSensorRequest;
import io.oferto.argo.client.model.StreamResultOfSensorLogEntry;
import io.oferto.argo.client.model.StreamResultOfSensorSensorWatchEvent;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SensorServiceApi
 */
@Ignore
public class SensorServiceApiTest {

    private final SensorServiceApi api = new SensorServiceApi();

    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sensorServiceCreateSensorTest() throws Exception {
        String namespace = null;
        SensorCreateSensorRequest body = null;
        IoArgoprojEventsV1alpha1Sensor response = api.sensorServiceCreateSensor(namespace, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sensorServiceDeleteSensorTest() throws Exception {
        String namespace = null;
        String name = null;
        String deleteOptionsGracePeriodSeconds = null;
        String deleteOptionsPreconditionsUid = null;
        String deleteOptionsPreconditionsResourceVersion = null;
        Boolean deleteOptionsOrphanDependents = null;
        String deleteOptionsPropagationPolicy = null;
        List<String> deleteOptionsDryRun = null;
        SensorDeleteSensorResponse response = api.sensorServiceDeleteSensor(namespace, name, deleteOptionsGracePeriodSeconds, deleteOptionsPreconditionsUid, deleteOptionsPreconditionsResourceVersion, deleteOptionsOrphanDependents, deleteOptionsPropagationPolicy, deleteOptionsDryRun);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sensorServiceGetSensorTest() throws Exception {
        String namespace = null;
        String name = null;
        String getOptionsResourceVersion = null;
        IoArgoprojEventsV1alpha1Sensor response = api.sensorServiceGetSensor(namespace, name, getOptionsResourceVersion);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sensorServiceListSensorsTest() throws Exception {
        String namespace = null;
        String listOptionsLabelSelector = null;
        String listOptionsFieldSelector = null;
        Boolean listOptionsWatch = null;
        Boolean listOptionsAllowWatchBookmarks = null;
        String listOptionsResourceVersion = null;
        String listOptionsResourceVersionMatch = null;
        String listOptionsTimeoutSeconds = null;
        String listOptionsLimit = null;
        String listOptionsContinue = null;
        IoArgoprojEventsV1alpha1SensorList response = api.sensorServiceListSensors(namespace, listOptionsLabelSelector, listOptionsFieldSelector, listOptionsWatch, listOptionsAllowWatchBookmarks, listOptionsResourceVersion, listOptionsResourceVersionMatch, listOptionsTimeoutSeconds, listOptionsLimit, listOptionsContinue);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sensorServiceSensorsLogsTest() throws Exception {
        String namespace = null;
        String name = null;
        String triggerName = null;
        String grep = null;
        String podLogOptionsContainer = null;
        Boolean podLogOptionsFollow = null;
        Boolean podLogOptionsPrevious = null;
        String podLogOptionsSinceSeconds = null;
        String podLogOptionsSinceTimeSeconds = null;
        Integer podLogOptionsSinceTimeNanos = null;
        Boolean podLogOptionsTimestamps = null;
        String podLogOptionsTailLines = null;
        String podLogOptionsLimitBytes = null;
        Boolean podLogOptionsInsecureSkipTLSVerifyBackend = null;
        StreamResultOfSensorLogEntry response = api.sensorServiceSensorsLogs(namespace, name, triggerName, grep, podLogOptionsContainer, podLogOptionsFollow, podLogOptionsPrevious, podLogOptionsSinceSeconds, podLogOptionsSinceTimeSeconds, podLogOptionsSinceTimeNanos, podLogOptionsTimestamps, podLogOptionsTailLines, podLogOptionsLimitBytes, podLogOptionsInsecureSkipTLSVerifyBackend);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sensorServiceUpdateSensorTest() throws Exception {
        String namespace = null;
        String name = null;
        SensorUpdateSensorRequest body = null;
        IoArgoprojEventsV1alpha1Sensor response = api.sensorServiceUpdateSensor(namespace, name, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sensorServiceWatchSensorsTest() throws Exception {
        String namespace = null;
        String listOptionsLabelSelector = null;
        String listOptionsFieldSelector = null;
        Boolean listOptionsWatch = null;
        Boolean listOptionsAllowWatchBookmarks = null;
        String listOptionsResourceVersion = null;
        String listOptionsResourceVersionMatch = null;
        String listOptionsTimeoutSeconds = null;
        String listOptionsLimit = null;
        String listOptionsContinue = null;
        StreamResultOfSensorSensorWatchEvent response = api.sensorServiceWatchSensors(namespace, listOptionsLabelSelector, listOptionsFieldSelector, listOptionsWatch, listOptionsAllowWatchBookmarks, listOptionsResourceVersion, listOptionsResourceVersionMatch, listOptionsTimeoutSeconds, listOptionsLimit, listOptionsContinue);

        // TODO: test validations
    }
    
}
