/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.api;

import io.oferto.argo.client.api.WorkflowTemplateServiceApi;
import io.oferto.argo.client.model.GrpcGatewayRuntimeError;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1WorkflowTemplate;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1WorkflowTemplateCreateRequest;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1WorkflowTemplateDeleteResponse;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1WorkflowTemplateList;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1WorkflowTemplateUpdateRequest;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkflowTemplateServiceApi
 */
@Ignore
public class WorkflowTemplateServiceApiTest {

    private final WorkflowTemplateServiceApi api = new WorkflowTemplateServiceApi();

    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void workflowTemplateServiceCreateWorkflowTemplateTest() throws Exception {
        String namespace = null;
        IoArgoprojWorkflowV1alpha1WorkflowTemplateCreateRequest body = null;
        IoArgoprojWorkflowV1alpha1WorkflowTemplate response = api.workflowTemplateServiceCreateWorkflowTemplate(namespace, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void workflowTemplateServiceDeleteWorkflowTemplateTest() throws Exception {
        String namespace = null;
        String name = null;
        String deleteOptionsGracePeriodSeconds = null;
        String deleteOptionsPreconditionsUid = null;
        String deleteOptionsPreconditionsResourceVersion = null;
        Boolean deleteOptionsOrphanDependents = null;
        String deleteOptionsPropagationPolicy = null;
        List<String> deleteOptionsDryRun = null;
        IoArgoprojWorkflowV1alpha1WorkflowTemplateDeleteResponse response = api.workflowTemplateServiceDeleteWorkflowTemplate(namespace, name, deleteOptionsGracePeriodSeconds, deleteOptionsPreconditionsUid, deleteOptionsPreconditionsResourceVersion, deleteOptionsOrphanDependents, deleteOptionsPropagationPolicy, deleteOptionsDryRun);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void workflowTemplateServiceGetWorkflowTemplateTest() throws Exception {
        String namespace = null;
        String name = null;
        String getOptionsResourceVersion = null;
        IoArgoprojWorkflowV1alpha1WorkflowTemplate response = api.workflowTemplateServiceGetWorkflowTemplate(namespace, name, getOptionsResourceVersion);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void workflowTemplateServiceLintWorkflowTemplateTest() throws Exception {
        String namespace = null;
        IoArgoprojWorkflowV1alpha1WorkflowTemplateLintRequest body = null;
        IoArgoprojWorkflowV1alpha1WorkflowTemplate response = api.workflowTemplateServiceLintWorkflowTemplate(namespace, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void workflowTemplateServiceListWorkflowTemplatesTest() throws Exception {
        String namespace = null;
        String namePattern = null;
        String listOptionsLabelSelector = null;
        String listOptionsFieldSelector = null;
        Boolean listOptionsWatch = null;
        Boolean listOptionsAllowWatchBookmarks = null;
        String listOptionsResourceVersion = null;
        String listOptionsResourceVersionMatch = null;
        String listOptionsTimeoutSeconds = null;
        String listOptionsLimit = null;
        String listOptionsContinue = null;
        IoArgoprojWorkflowV1alpha1WorkflowTemplateList response = api.workflowTemplateServiceListWorkflowTemplates(namespace, namePattern, listOptionsLabelSelector, listOptionsFieldSelector, listOptionsWatch, listOptionsAllowWatchBookmarks, listOptionsResourceVersion, listOptionsResourceVersionMatch, listOptionsTimeoutSeconds, listOptionsLimit, listOptionsContinue);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void workflowTemplateServiceUpdateWorkflowTemplateTest() throws Exception {
        String namespace = null;
        String name = null;
        IoArgoprojWorkflowV1alpha1WorkflowTemplateUpdateRequest body = null;
        IoArgoprojWorkflowV1alpha1WorkflowTemplate response = api.workflowTemplateServiceUpdateWorkflowTemplate(namespace, name, body);

        // TODO: test validations
    }
    
}
