/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.oferto.argo.client.model.GoogleProtobufAny;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GrpcGatewayRuntimeStreamError
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class GrpcGatewayRuntimeStreamError {
  @SerializedName("details")
  private List<GoogleProtobufAny> details = null;

  @SerializedName("grpc_code")
  private Integer grpcCode = null;

  @SerializedName("http_code")
  private Integer httpCode = null;

  @SerializedName("http_status")
  private String httpStatus = null;

  @SerializedName("message")
  private String message = null;

  public GrpcGatewayRuntimeStreamError details(List<GoogleProtobufAny> details) {
    this.details = details;
    return this;
  }

  public GrpcGatewayRuntimeStreamError addDetailsItem(GoogleProtobufAny detailsItem) {
    if (this.details == null) {
      this.details = new ArrayList<GoogleProtobufAny>();
    }
    this.details.add(detailsItem);
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @ApiModelProperty(value = "")
  public List<GoogleProtobufAny> getDetails() {
    return details;
  }

  public void setDetails(List<GoogleProtobufAny> details) {
    this.details = details;
  }

  public GrpcGatewayRuntimeStreamError grpcCode(Integer grpcCode) {
    this.grpcCode = grpcCode;
    return this;
  }

   /**
   * Get grpcCode
   * @return grpcCode
  **/
  @ApiModelProperty(value = "")
  public Integer getGrpcCode() {
    return grpcCode;
  }

  public void setGrpcCode(Integer grpcCode) {
    this.grpcCode = grpcCode;
  }

  public GrpcGatewayRuntimeStreamError httpCode(Integer httpCode) {
    this.httpCode = httpCode;
    return this;
  }

   /**
   * Get httpCode
   * @return httpCode
  **/
  @ApiModelProperty(value = "")
  public Integer getHttpCode() {
    return httpCode;
  }

  public void setHttpCode(Integer httpCode) {
    this.httpCode = httpCode;
  }

  public GrpcGatewayRuntimeStreamError httpStatus(String httpStatus) {
    this.httpStatus = httpStatus;
    return this;
  }

   /**
   * Get httpStatus
   * @return httpStatus
  **/
  @ApiModelProperty(value = "")
  public String getHttpStatus() {
    return httpStatus;
  }

  public void setHttpStatus(String httpStatus) {
    this.httpStatus = httpStatus;
  }

  public GrpcGatewayRuntimeStreamError message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GrpcGatewayRuntimeStreamError grpcGatewayRuntimeStreamError = (GrpcGatewayRuntimeStreamError) o;
    return Objects.equals(this.details, grpcGatewayRuntimeStreamError.details) &&
        Objects.equals(this.grpcCode, grpcGatewayRuntimeStreamError.grpcCode) &&
        Objects.equals(this.httpCode, grpcGatewayRuntimeStreamError.httpCode) &&
        Objects.equals(this.httpStatus, grpcGatewayRuntimeStreamError.httpStatus) &&
        Objects.equals(this.message, grpcGatewayRuntimeStreamError.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(details, grpcCode, httpCode, httpStatus, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GrpcGatewayRuntimeStreamError {\n");
    
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    grpcCode: ").append(toIndentedString(grpcCode)).append("\n");
    sb.append("    httpCode: ").append(toIndentedString(httpCode)).append("\n");
    sb.append("    httpStatus: ").append(toIndentedString(httpStatus)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

