/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.oferto.argo.client.model.IoK8sApiCoreV1ServicePort;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * IoArgoprojEventsV1alpha1Service
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojEventsV1alpha1Service {
  @SerializedName("clusterIP")
  private String clusterIP = null;

  @SerializedName("ports")
  private List<IoK8sApiCoreV1ServicePort> ports = null;

  public IoArgoprojEventsV1alpha1Service clusterIP(String clusterIP) {
    this.clusterIP = clusterIP;
    return this;
  }

   /**
   * Get clusterIP
   * @return clusterIP
  **/
  @ApiModelProperty(value = "")
  public String getClusterIP() {
    return clusterIP;
  }

  public void setClusterIP(String clusterIP) {
    this.clusterIP = clusterIP;
  }

  public IoArgoprojEventsV1alpha1Service ports(List<IoK8sApiCoreV1ServicePort> ports) {
    this.ports = ports;
    return this;
  }

  public IoArgoprojEventsV1alpha1Service addPortsItem(IoK8sApiCoreV1ServicePort portsItem) {
    if (this.ports == null) {
      this.ports = new ArrayList<IoK8sApiCoreV1ServicePort>();
    }
    this.ports.add(portsItem);
    return this;
  }

   /**
   * Get ports
   * @return ports
  **/
  @ApiModelProperty(value = "")
  public List<IoK8sApiCoreV1ServicePort> getPorts() {
    return ports;
  }

  public void setPorts(List<IoK8sApiCoreV1ServicePort> ports) {
    this.ports = ports;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojEventsV1alpha1Service ioArgoprojEventsV1alpha1Service = (IoArgoprojEventsV1alpha1Service) o;
    return Objects.equals(this.clusterIP, ioArgoprojEventsV1alpha1Service.clusterIP) &&
        Objects.equals(this.ports, ioArgoprojEventsV1alpha1Service.ports);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clusterIP, ports);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojEventsV1alpha1Service {\n");
    
    sb.append("    clusterIP: ").append(toIndentedString(clusterIP)).append("\n");
    sb.append("    ports: ").append(toIndentedString(ports)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

