/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1HTTPAuth;
import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1Header;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * HTTPArtifact allows a file served on HTTP to be placed as an input artifact in a container
 */
@ApiModel(description = "HTTPArtifact allows a file served on HTTP to be placed as an input artifact in a container")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojWorkflowV1alpha1HTTPArtifact {
  @SerializedName("auth")
  private IoArgoprojWorkflowV1alpha1HTTPAuth auth = null;

  @SerializedName("headers")
  private List<IoArgoprojWorkflowV1alpha1Header> headers = null;

  @SerializedName("url")
  private String url = null;

  public IoArgoprojWorkflowV1alpha1HTTPArtifact auth(IoArgoprojWorkflowV1alpha1HTTPAuth auth) {
    this.auth = auth;
    return this;
  }

   /**
   * Auth contains information for client authentication
   * @return auth
  **/
  @ApiModelProperty(value = "Auth contains information for client authentication")
  public IoArgoprojWorkflowV1alpha1HTTPAuth getAuth() {
    return auth;
  }

  public void setAuth(IoArgoprojWorkflowV1alpha1HTTPAuth auth) {
    this.auth = auth;
  }

  public IoArgoprojWorkflowV1alpha1HTTPArtifact headers(List<IoArgoprojWorkflowV1alpha1Header> headers) {
    this.headers = headers;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1HTTPArtifact addHeadersItem(IoArgoprojWorkflowV1alpha1Header headersItem) {
    if (this.headers == null) {
      this.headers = new ArrayList<IoArgoprojWorkflowV1alpha1Header>();
    }
    this.headers.add(headersItem);
    return this;
  }

   /**
   * Headers are an optional list of headers to send with HTTP requests for artifacts
   * @return headers
  **/
  @ApiModelProperty(value = "Headers are an optional list of headers to send with HTTP requests for artifacts")
  public List<IoArgoprojWorkflowV1alpha1Header> getHeaders() {
    return headers;
  }

  public void setHeaders(List<IoArgoprojWorkflowV1alpha1Header> headers) {
    this.headers = headers;
  }

  public IoArgoprojWorkflowV1alpha1HTTPArtifact url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL of the artifact
   * @return url
  **/
  @ApiModelProperty(required = true, value = "URL of the artifact")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1HTTPArtifact ioArgoprojWorkflowV1alpha1HTTPArtifact = (IoArgoprojWorkflowV1alpha1HTTPArtifact) o;
    return Objects.equals(this.auth, ioArgoprojWorkflowV1alpha1HTTPArtifact.auth) &&
        Objects.equals(this.headers, ioArgoprojWorkflowV1alpha1HTTPArtifact.headers) &&
        Objects.equals(this.url, ioArgoprojWorkflowV1alpha1HTTPArtifact.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auth, headers, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1HTTPArtifact {\n");
    
    sb.append("    auth: ").append(toIndentedString(auth)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

