/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IoArgoprojEventsV1alpha1AMQPConsumeConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojEventsV1alpha1AMQPConsumeConfig {
  @SerializedName("autoAck")
  private Boolean autoAck = null;

  @SerializedName("consumerTag")
  private String consumerTag = null;

  @SerializedName("exclusive")
  private Boolean exclusive = null;

  @SerializedName("noLocal")
  private Boolean noLocal = null;

  @SerializedName("noWait")
  private Boolean noWait = null;

  public IoArgoprojEventsV1alpha1AMQPConsumeConfig autoAck(Boolean autoAck) {
    this.autoAck = autoAck;
    return this;
  }

   /**
   * Get autoAck
   * @return autoAck
  **/
  @ApiModelProperty(value = "")
  public Boolean isAutoAck() {
    return autoAck;
  }

  public void setAutoAck(Boolean autoAck) {
    this.autoAck = autoAck;
  }

  public IoArgoprojEventsV1alpha1AMQPConsumeConfig consumerTag(String consumerTag) {
    this.consumerTag = consumerTag;
    return this;
  }

   /**
   * Get consumerTag
   * @return consumerTag
  **/
  @ApiModelProperty(value = "")
  public String getConsumerTag() {
    return consumerTag;
  }

  public void setConsumerTag(String consumerTag) {
    this.consumerTag = consumerTag;
  }

  public IoArgoprojEventsV1alpha1AMQPConsumeConfig exclusive(Boolean exclusive) {
    this.exclusive = exclusive;
    return this;
  }

   /**
   * Get exclusive
   * @return exclusive
  **/
  @ApiModelProperty(value = "")
  public Boolean isExclusive() {
    return exclusive;
  }

  public void setExclusive(Boolean exclusive) {
    this.exclusive = exclusive;
  }

  public IoArgoprojEventsV1alpha1AMQPConsumeConfig noLocal(Boolean noLocal) {
    this.noLocal = noLocal;
    return this;
  }

   /**
   * Get noLocal
   * @return noLocal
  **/
  @ApiModelProperty(value = "")
  public Boolean isNoLocal() {
    return noLocal;
  }

  public void setNoLocal(Boolean noLocal) {
    this.noLocal = noLocal;
  }

  public IoArgoprojEventsV1alpha1AMQPConsumeConfig noWait(Boolean noWait) {
    this.noWait = noWait;
    return this;
  }

   /**
   * Get noWait
   * @return noWait
  **/
  @ApiModelProperty(value = "")
  public Boolean isNoWait() {
    return noWait;
  }

  public void setNoWait(Boolean noWait) {
    this.noWait = noWait;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojEventsV1alpha1AMQPConsumeConfig ioArgoprojEventsV1alpha1AMQPConsumeConfig = (IoArgoprojEventsV1alpha1AMQPConsumeConfig) o;
    return Objects.equals(this.autoAck, ioArgoprojEventsV1alpha1AMQPConsumeConfig.autoAck) &&
        Objects.equals(this.consumerTag, ioArgoprojEventsV1alpha1AMQPConsumeConfig.consumerTag) &&
        Objects.equals(this.exclusive, ioArgoprojEventsV1alpha1AMQPConsumeConfig.exclusive) &&
        Objects.equals(this.noLocal, ioArgoprojEventsV1alpha1AMQPConsumeConfig.noLocal) &&
        Objects.equals(this.noWait, ioArgoprojEventsV1alpha1AMQPConsumeConfig.noWait);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoAck, consumerTag, exclusive, noLocal, noWait);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojEventsV1alpha1AMQPConsumeConfig {\n");
    
    sb.append("    autoAck: ").append(toIndentedString(autoAck)).append("\n");
    sb.append("    consumerTag: ").append(toIndentedString(consumerTag)).append("\n");
    sb.append("    exclusive: ").append(toIndentedString(exclusive)).append("\n");
    sb.append("    noLocal: ").append(toIndentedString(noLocal)).append("\n");
    sb.append("    noWait: ").append(toIndentedString(noWait)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

