/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1SuppliedValueFrom;
import io.oferto.argo.client.model.IoK8sApiCoreV1ConfigMapKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;

/**
 * ValueFrom describes a location in which to obtain the value to a parameter
 */
@ApiModel(description = "ValueFrom describes a location in which to obtain the value to a parameter")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojWorkflowV1alpha1ValueFrom {
  @SerializedName("configMapKeyRef")
  private IoK8sApiCoreV1ConfigMapKeySelector configMapKeyRef = null;

  @SerializedName("default")
  private String _default = null;

  @SerializedName("event")
  private String event = null;

  @SerializedName("expression")
  private String expression = null;

  @SerializedName("jqFilter")
  private String jqFilter = null;

  @SerializedName("jsonPath")
  private String jsonPath = null;

  @SerializedName("parameter")
  private String parameter = null;

  @SerializedName("path")
  private String path = null;

  @SerializedName("supplied")
  private IoArgoprojWorkflowV1alpha1SuppliedValueFrom supplied = null;

  public IoArgoprojWorkflowV1alpha1ValueFrom configMapKeyRef(IoK8sApiCoreV1ConfigMapKeySelector configMapKeyRef) {
    this.configMapKeyRef = configMapKeyRef;
    return this;
  }

   /**
   * ConfigMapKeyRef is configmap selector for input parameter configuration
   * @return configMapKeyRef
  **/
  @ApiModelProperty(value = "ConfigMapKeyRef is configmap selector for input parameter configuration")
  public IoK8sApiCoreV1ConfigMapKeySelector getConfigMapKeyRef() {
    return configMapKeyRef;
  }

  public void setConfigMapKeyRef(IoK8sApiCoreV1ConfigMapKeySelector configMapKeyRef) {
    this.configMapKeyRef = configMapKeyRef;
  }

  public IoArgoprojWorkflowV1alpha1ValueFrom _default(String _default) {
    this._default = _default;
    return this;
  }

   /**
   * Default specifies a value to be used if retrieving the value from the specified source fails
   * @return _default
  **/
  @ApiModelProperty(value = "Default specifies a value to be used if retrieving the value from the specified source fails")
  public String getDefault() {
    return _default;
  }

  public void setDefault(String _default) {
    this._default = _default;
  }

  public IoArgoprojWorkflowV1alpha1ValueFrom event(String event) {
    this.event = event;
    return this;
  }

   /**
   * Selector (https://github.com/antonmedv/expr) that is evaluated against the event to get the value of the parameter. E.g. &#x60;payload.message&#x60;
   * @return event
  **/
  @ApiModelProperty(value = "Selector (https://github.com/antonmedv/expr) that is evaluated against the event to get the value of the parameter. E.g. `payload.message`")
  public String getEvent() {
    return event;
  }

  public void setEvent(String event) {
    this.event = event;
  }

  public IoArgoprojWorkflowV1alpha1ValueFrom expression(String expression) {
    this.expression = expression;
    return this;
  }

   /**
   * Expression, if defined, is evaluated to specify the value for the parameter
   * @return expression
  **/
  @ApiModelProperty(value = "Expression, if defined, is evaluated to specify the value for the parameter")
  public String getExpression() {
    return expression;
  }

  public void setExpression(String expression) {
    this.expression = expression;
  }

  public IoArgoprojWorkflowV1alpha1ValueFrom jqFilter(String jqFilter) {
    this.jqFilter = jqFilter;
    return this;
  }

   /**
   * JQFilter expression against the resource object in resource templates
   * @return jqFilter
  **/
  @ApiModelProperty(value = "JQFilter expression against the resource object in resource templates")
  public String getJqFilter() {
    return jqFilter;
  }

  public void setJqFilter(String jqFilter) {
    this.jqFilter = jqFilter;
  }

  public IoArgoprojWorkflowV1alpha1ValueFrom jsonPath(String jsonPath) {
    this.jsonPath = jsonPath;
    return this;
  }

   /**
   * JSONPath of a resource to retrieve an output parameter value from in resource templates
   * @return jsonPath
  **/
  @ApiModelProperty(value = "JSONPath of a resource to retrieve an output parameter value from in resource templates")
  public String getJsonPath() {
    return jsonPath;
  }

  public void setJsonPath(String jsonPath) {
    this.jsonPath = jsonPath;
  }

  public IoArgoprojWorkflowV1alpha1ValueFrom parameter(String parameter) {
    this.parameter = parameter;
    return this;
  }

   /**
   * Parameter reference to a step or dag task in which to retrieve an output parameter value from (e.g. &#39;{{steps.mystep.outputs.myparam}}&#39;)
   * @return parameter
  **/
  @ApiModelProperty(value = "Parameter reference to a step or dag task in which to retrieve an output parameter value from (e.g. '{{steps.mystep.outputs.myparam}}')")
  public String getParameter() {
    return parameter;
  }

  public void setParameter(String parameter) {
    this.parameter = parameter;
  }

  public IoArgoprojWorkflowV1alpha1ValueFrom path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Path in the container to retrieve an output parameter value from in container templates
   * @return path
  **/
  @ApiModelProperty(value = "Path in the container to retrieve an output parameter value from in container templates")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public IoArgoprojWorkflowV1alpha1ValueFrom supplied(IoArgoprojWorkflowV1alpha1SuppliedValueFrom supplied) {
    this.supplied = supplied;
    return this;
  }

   /**
   * Supplied value to be filled in directly, either through the CLI, API, etc.
   * @return supplied
  **/
  @ApiModelProperty(value = "Supplied value to be filled in directly, either through the CLI, API, etc.")
  public IoArgoprojWorkflowV1alpha1SuppliedValueFrom getSupplied() {
    return supplied;
  }

  public void setSupplied(IoArgoprojWorkflowV1alpha1SuppliedValueFrom supplied) {
    this.supplied = supplied;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1ValueFrom ioArgoprojWorkflowV1alpha1ValueFrom = (IoArgoprojWorkflowV1alpha1ValueFrom) o;
    return Objects.equals(this.configMapKeyRef, ioArgoprojWorkflowV1alpha1ValueFrom.configMapKeyRef) &&
        Objects.equals(this._default, ioArgoprojWorkflowV1alpha1ValueFrom._default) &&
        Objects.equals(this.event, ioArgoprojWorkflowV1alpha1ValueFrom.event) &&
        Objects.equals(this.expression, ioArgoprojWorkflowV1alpha1ValueFrom.expression) &&
        Objects.equals(this.jqFilter, ioArgoprojWorkflowV1alpha1ValueFrom.jqFilter) &&
        Objects.equals(this.jsonPath, ioArgoprojWorkflowV1alpha1ValueFrom.jsonPath) &&
        Objects.equals(this.parameter, ioArgoprojWorkflowV1alpha1ValueFrom.parameter) &&
        Objects.equals(this.path, ioArgoprojWorkflowV1alpha1ValueFrom.path) &&
        Objects.equals(this.supplied, ioArgoprojWorkflowV1alpha1ValueFrom.supplied);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configMapKeyRef, _default, event, expression, jqFilter, jsonPath, parameter, path, supplied);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1ValueFrom {\n");
    
    sb.append("    configMapKeyRef: ").append(toIndentedString(configMapKeyRef)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("    jqFilter: ").append(toIndentedString(jqFilter)).append("\n");
    sb.append("    jsonPath: ").append(toIndentedString(jsonPath)).append("\n");
    sb.append("    parameter: ").append(toIndentedString(parameter)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    supplied: ").append(toIndentedString(supplied)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

