/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IoArgoprojEventsV1alpha1RateLimit
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojEventsV1alpha1RateLimit {
  @SerializedName("requestsPerUnit")
  private Integer requestsPerUnit = null;

  @SerializedName("unit")
  private String unit = null;

  public IoArgoprojEventsV1alpha1RateLimit requestsPerUnit(Integer requestsPerUnit) {
    this.requestsPerUnit = requestsPerUnit;
    return this;
  }

   /**
   * Get requestsPerUnit
   * @return requestsPerUnit
  **/
  @ApiModelProperty(value = "")
  public Integer getRequestsPerUnit() {
    return requestsPerUnit;
  }

  public void setRequestsPerUnit(Integer requestsPerUnit) {
    this.requestsPerUnit = requestsPerUnit;
  }

  public IoArgoprojEventsV1alpha1RateLimit unit(String unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @ApiModelProperty(value = "")
  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojEventsV1alpha1RateLimit ioArgoprojEventsV1alpha1RateLimit = (IoArgoprojEventsV1alpha1RateLimit) o;
    return Objects.equals(this.requestsPerUnit, ioArgoprojEventsV1alpha1RateLimit.requestsPerUnit) &&
        Objects.equals(this.unit, ioArgoprojEventsV1alpha1RateLimit.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestsPerUnit, unit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojEventsV1alpha1RateLimit {\n");
    
    sb.append("    requestsPerUnit: ").append(toIndentedString(requestsPerUnit)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

