/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1ValueFrom;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Parameter indicate a passed string parameter to a service template with an optional default value
 */
@ApiModel(description = "Parameter indicate a passed string parameter to a service template with an optional default value")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojWorkflowV1alpha1Parameter {
  @SerializedName("default")
  private String _default = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("enum")
  private List<String> _enum = null;

  @SerializedName("globalName")
  private String globalName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("valueFrom")
  private IoArgoprojWorkflowV1alpha1ValueFrom valueFrom = null;

  public IoArgoprojWorkflowV1alpha1Parameter _default(String _default) {
    this._default = _default;
    return this;
  }

   /**
   * Default is the default value to use for an input parameter if a value was not supplied
   * @return _default
  **/
  @ApiModelProperty(value = "Default is the default value to use for an input parameter if a value was not supplied")
  public String getDefault() {
    return _default;
  }

  public void setDefault(String _default) {
    this._default = _default;
  }

  public IoArgoprojWorkflowV1alpha1Parameter description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description is the parameter description
   * @return description
  **/
  @ApiModelProperty(value = "Description is the parameter description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public IoArgoprojWorkflowV1alpha1Parameter _enum(List<String> _enum) {
    this._enum = _enum;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1Parameter addEnumItem(String _enumItem) {
    if (this._enum == null) {
      this._enum = new ArrayList<String>();
    }
    this._enum.add(_enumItem);
    return this;
  }

   /**
   * Enum holds a list of string values to choose from, for the actual value of the parameter
   * @return _enum
  **/
  @ApiModelProperty(value = "Enum holds a list of string values to choose from, for the actual value of the parameter")
  public List<String> getEnum() {
    return _enum;
  }

  public void setEnum(List<String> _enum) {
    this._enum = _enum;
  }

  public IoArgoprojWorkflowV1alpha1Parameter globalName(String globalName) {
    this.globalName = globalName;
    return this;
  }

   /**
   * GlobalName exports an output parameter to the global scope, making it available as &#39;{{io.argoproj.workflow.v1alpha1.outputs.parameters.XXXX}} and in workflow.status.outputs.parameters
   * @return globalName
  **/
  @ApiModelProperty(value = "GlobalName exports an output parameter to the global scope, making it available as '{{io.argoproj.workflow.v1alpha1.outputs.parameters.XXXX}} and in workflow.status.outputs.parameters")
  public String getGlobalName() {
    return globalName;
  }

  public void setGlobalName(String globalName) {
    this.globalName = globalName;
  }

  public IoArgoprojWorkflowV1alpha1Parameter name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name is the parameter name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name is the parameter name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IoArgoprojWorkflowV1alpha1Parameter value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Value is the literal value to use for the parameter. If specified in the context of an input parameter, the value takes precedence over any passed values
   * @return value
  **/
  @ApiModelProperty(value = "Value is the literal value to use for the parameter. If specified in the context of an input parameter, the value takes precedence over any passed values")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public IoArgoprojWorkflowV1alpha1Parameter valueFrom(IoArgoprojWorkflowV1alpha1ValueFrom valueFrom) {
    this.valueFrom = valueFrom;
    return this;
  }

   /**
   * ValueFrom is the source for the output parameter&#39;s value
   * @return valueFrom
  **/
  @ApiModelProperty(value = "ValueFrom is the source for the output parameter's value")
  public IoArgoprojWorkflowV1alpha1ValueFrom getValueFrom() {
    return valueFrom;
  }

  public void setValueFrom(IoArgoprojWorkflowV1alpha1ValueFrom valueFrom) {
    this.valueFrom = valueFrom;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1Parameter ioArgoprojWorkflowV1alpha1Parameter = (IoArgoprojWorkflowV1alpha1Parameter) o;
    return Objects.equals(this._default, ioArgoprojWorkflowV1alpha1Parameter._default) &&
        Objects.equals(this.description, ioArgoprojWorkflowV1alpha1Parameter.description) &&
        Objects.equals(this._enum, ioArgoprojWorkflowV1alpha1Parameter._enum) &&
        Objects.equals(this.globalName, ioArgoprojWorkflowV1alpha1Parameter.globalName) &&
        Objects.equals(this.name, ioArgoprojWorkflowV1alpha1Parameter.name) &&
        Objects.equals(this.value, ioArgoprojWorkflowV1alpha1Parameter.value) &&
        Objects.equals(this.valueFrom, ioArgoprojWorkflowV1alpha1Parameter.valueFrom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_default, description, _enum, globalName, name, value, valueFrom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1Parameter {\n");
    
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    _enum: ").append(toIndentedString(_enum)).append("\n");
    sb.append("    globalName: ").append(toIndentedString(globalName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valueFrom: ").append(toIndentedString(valueFrom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

