/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig {
  @SerializedName("arguments")
  private String arguments = null;

  @SerializedName("autoDelete")
  private Boolean autoDelete = null;

  @SerializedName("durable")
  private Boolean durable = null;

  @SerializedName("exclusive")
  private Boolean exclusive = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("noWait")
  private Boolean noWait = null;

  public IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig arguments(String arguments) {
    this.arguments = arguments;
    return this;
  }

   /**
   * Get arguments
   * @return arguments
  **/
  @ApiModelProperty(value = "")
  public String getArguments() {
    return arguments;
  }

  public void setArguments(String arguments) {
    this.arguments = arguments;
  }

  public IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig autoDelete(Boolean autoDelete) {
    this.autoDelete = autoDelete;
    return this;
  }

   /**
   * Get autoDelete
   * @return autoDelete
  **/
  @ApiModelProperty(value = "")
  public Boolean isAutoDelete() {
    return autoDelete;
  }

  public void setAutoDelete(Boolean autoDelete) {
    this.autoDelete = autoDelete;
  }

  public IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig durable(Boolean durable) {
    this.durable = durable;
    return this;
  }

   /**
   * Get durable
   * @return durable
  **/
  @ApiModelProperty(value = "")
  public Boolean isDurable() {
    return durable;
  }

  public void setDurable(Boolean durable) {
    this.durable = durable;
  }

  public IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig exclusive(Boolean exclusive) {
    this.exclusive = exclusive;
    return this;
  }

   /**
   * Get exclusive
   * @return exclusive
  **/
  @ApiModelProperty(value = "")
  public Boolean isExclusive() {
    return exclusive;
  }

  public void setExclusive(Boolean exclusive) {
    this.exclusive = exclusive;
  }

  public IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig noWait(Boolean noWait) {
    this.noWait = noWait;
    return this;
  }

   /**
   * Get noWait
   * @return noWait
  **/
  @ApiModelProperty(value = "")
  public Boolean isNoWait() {
    return noWait;
  }

  public void setNoWait(Boolean noWait) {
    this.noWait = noWait;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig ioArgoprojEventsV1alpha1AMQPQueueDeclareConfig = (IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig) o;
    return Objects.equals(this.arguments, ioArgoprojEventsV1alpha1AMQPQueueDeclareConfig.arguments) &&
        Objects.equals(this.autoDelete, ioArgoprojEventsV1alpha1AMQPQueueDeclareConfig.autoDelete) &&
        Objects.equals(this.durable, ioArgoprojEventsV1alpha1AMQPQueueDeclareConfig.durable) &&
        Objects.equals(this.exclusive, ioArgoprojEventsV1alpha1AMQPQueueDeclareConfig.exclusive) &&
        Objects.equals(this.name, ioArgoprojEventsV1alpha1AMQPQueueDeclareConfig.name) &&
        Objects.equals(this.noWait, ioArgoprojEventsV1alpha1AMQPQueueDeclareConfig.noWait);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arguments, autoDelete, durable, exclusive, name, noWait);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojEventsV1alpha1AMQPQueueDeclareConfig {\n");
    
    sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
    sb.append("    autoDelete: ").append(toIndentedString(autoDelete)).append("\n");
    sb.append("    durable: ").append(toIndentedString(durable)).append("\n");
    sb.append("    exclusive: ").append(toIndentedString(exclusive)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    noWait: ").append(toIndentedString(noWait)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

