/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MutexHolding describes the mutex and the object which is holding it.
 */
@ApiModel(description = "MutexHolding describes the mutex and the object which is holding it.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojWorkflowV1alpha1MutexHolding {
  @SerializedName("holder")
  private String holder = null;

  @SerializedName("mutex")
  private String mutex = null;

  public IoArgoprojWorkflowV1alpha1MutexHolding holder(String holder) {
    this.holder = holder;
    return this;
  }

   /**
   * Holder is a reference to the object which holds the Mutex. Holding Scenario:   1. Current workflow&#39;s NodeID which is holding the lock.      e.g: ${NodeID} Waiting Scenario:   1. Current workflow or other workflow NodeID which is holding the lock.      e.g: ${WorkflowName}/${NodeID}
   * @return holder
  **/
  @ApiModelProperty(value = "Holder is a reference to the object which holds the Mutex. Holding Scenario:   1. Current workflow's NodeID which is holding the lock.      e.g: ${NodeID} Waiting Scenario:   1. Current workflow or other workflow NodeID which is holding the lock.      e.g: ${WorkflowName}/${NodeID}")
  public String getHolder() {
    return holder;
  }

  public void setHolder(String holder) {
    this.holder = holder;
  }

  public IoArgoprojWorkflowV1alpha1MutexHolding mutex(String mutex) {
    this.mutex = mutex;
    return this;
  }

   /**
   * Reference for the mutex e.g: ${namespace}/mutex/${mutexName}
   * @return mutex
  **/
  @ApiModelProperty(value = "Reference for the mutex e.g: ${namespace}/mutex/${mutexName}")
  public String getMutex() {
    return mutex;
  }

  public void setMutex(String mutex) {
    this.mutex = mutex;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1MutexHolding ioArgoprojWorkflowV1alpha1MutexHolding = (IoArgoprojWorkflowV1alpha1MutexHolding) o;
    return Objects.equals(this.holder, ioArgoprojWorkflowV1alpha1MutexHolding.holder) &&
        Objects.equals(this.mutex, ioArgoprojWorkflowV1alpha1MutexHolding.mutex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(holder, mutex);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1MutexHolding {\n");
    
    sb.append("    holder: ").append(toIndentedString(holder)).append("\n");
    sb.append("    mutex: ").append(toIndentedString(mutex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

