/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.oferto.argo.client.model.IoK8sApiCoreV1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;

/**
 * IoArgoprojEventsV1alpha1BitbucketBasicAuth
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojEventsV1alpha1BitbucketBasicAuth {
  @SerializedName("password")
  private IoK8sApiCoreV1SecretKeySelector password = null;

  @SerializedName("username")
  private IoK8sApiCoreV1SecretKeySelector username = null;

  public IoArgoprojEventsV1alpha1BitbucketBasicAuth password(IoK8sApiCoreV1SecretKeySelector password) {
    this.password = password;
    return this;
  }

   /**
   * Password refers to the K8s secret that holds the password.
   * @return password
  **/
  @ApiModelProperty(value = "Password refers to the K8s secret that holds the password.")
  public IoK8sApiCoreV1SecretKeySelector getPassword() {
    return password;
  }

  public void setPassword(IoK8sApiCoreV1SecretKeySelector password) {
    this.password = password;
  }

  public IoArgoprojEventsV1alpha1BitbucketBasicAuth username(IoK8sApiCoreV1SecretKeySelector username) {
    this.username = username;
    return this;
  }

   /**
   * Username refers to the K8s secret that holds the username.
   * @return username
  **/
  @ApiModelProperty(value = "Username refers to the K8s secret that holds the username.")
  public IoK8sApiCoreV1SecretKeySelector getUsername() {
    return username;
  }

  public void setUsername(IoK8sApiCoreV1SecretKeySelector username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojEventsV1alpha1BitbucketBasicAuth ioArgoprojEventsV1alpha1BitbucketBasicAuth = (IoArgoprojEventsV1alpha1BitbucketBasicAuth) o;
    return Objects.equals(this.password, ioArgoprojEventsV1alpha1BitbucketBasicAuth.password) &&
        Objects.equals(this.username, ioArgoprojEventsV1alpha1BitbucketBasicAuth.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojEventsV1alpha1BitbucketBasicAuth {\n");
    
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

