/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef {
  @SerializedName("configMap")
  private String configMap = null;

  @SerializedName("key")
  private String key = null;

  public IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef configMap(String configMap) {
    this.configMap = configMap;
    return this;
  }

   /**
   * The name of the config map. Defaults to \&quot;artifact-repositories\&quot;.
   * @return configMap
  **/
  @ApiModelProperty(value = "The name of the config map. Defaults to \"artifact-repositories\".")
  public String getConfigMap() {
    return configMap;
  }

  public void setConfigMap(String configMap) {
    this.configMap = configMap;
  }

  public IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef key(String key) {
    this.key = key;
    return this;
  }

   /**
   * The config map key. Defaults to the value of the \&quot;workflows.argoproj.io/default-artifact-repository\&quot; annotation.
   * @return key
  **/
  @ApiModelProperty(value = "The config map key. Defaults to the value of the \"workflows.argoproj.io/default-artifact-repository\" annotation.")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef ioArgoprojWorkflowV1alpha1ArtifactRepositoryRef = (IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef) o;
    return Objects.equals(this.configMap, ioArgoprojWorkflowV1alpha1ArtifactRepositoryRef.configMap) &&
        Objects.equals(this.key, ioArgoprojWorkflowV1alpha1ArtifactRepositoryRef.key);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configMap, key);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef {\n");
    
    sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

