/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy {
  @SerializedName("duration")
  private String duration = null;

  @SerializedName("retries")
  private String retries = null;

  public IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Duration is the time between each retry, examples values are \&quot;300ms\&quot;, \&quot;1s\&quot; or \&quot;5m\&quot;. Valid time units are \&quot;ns\&quot;, \&quot;us\&quot; (or \&quot;µs\&quot;), \&quot;ms\&quot;, \&quot;s\&quot;, \&quot;m\&quot;, \&quot;h\&quot;.
   * @return duration
  **/
  @ApiModelProperty(value = "Duration is the time between each retry, examples values are \"300ms\", \"1s\" or \"5m\". Valid time units are \"ns\", \"us\" (or \"µs\"), \"ms\", \"s\", \"m\", \"h\".")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy retries(String retries) {
    this.retries = retries;
    return this;
  }

   /**
   * Nbr of retries
   * @return retries
  **/
  @ApiModelProperty(required = true, value = "Nbr of retries")
  public String getRetries() {
    return retries;
  }

  public void setRetries(String retries) {
    this.retries = retries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy ioArgoprojWorkflowV1alpha1ContainerSetRetryStrategy = (IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy) o;
    return Objects.equals(this.duration, ioArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.duration) &&
        Objects.equals(this.retries, ioArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.retries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duration, retries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy {\n");
    
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    retries: ").append(toIndentedString(retries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

