/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.oferto.argo.client.model.IoArgoprojWorkflowV1alpha1ArtifactRepository;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;

/**
 * IoArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus {
  @SerializedName("artifactRepository")
  private IoArgoprojWorkflowV1alpha1ArtifactRepository artifactRepository = null;

  @SerializedName("configMap")
  private String configMap = null;

  @SerializedName("default")
  private Boolean _default = null;

  @SerializedName("key")
  private String key = null;

  @SerializedName("namespace")
  private String namespace = null;

  public IoArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus artifactRepository(IoArgoprojWorkflowV1alpha1ArtifactRepository artifactRepository) {
    this.artifactRepository = artifactRepository;
    return this;
  }

   /**
   * The repository the workflow will use. This maybe empty before v3.1.
   * @return artifactRepository
  **/
  @ApiModelProperty(value = "The repository the workflow will use. This maybe empty before v3.1.")
  public IoArgoprojWorkflowV1alpha1ArtifactRepository getArtifactRepository() {
    return artifactRepository;
  }

  public void setArtifactRepository(IoArgoprojWorkflowV1alpha1ArtifactRepository artifactRepository) {
    this.artifactRepository = artifactRepository;
  }

  public IoArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus configMap(String configMap) {
    this.configMap = configMap;
    return this;
  }

   /**
   * The name of the config map. Defaults to \&quot;artifact-repositories\&quot;.
   * @return configMap
  **/
  @ApiModelProperty(value = "The name of the config map. Defaults to \"artifact-repositories\".")
  public String getConfigMap() {
    return configMap;
  }

  public void setConfigMap(String configMap) {
    this.configMap = configMap;
  }

  public IoArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus _default(Boolean _default) {
    this._default = _default;
    return this;
  }

   /**
   * If this ref represents the default artifact repository, rather than a config map.
   * @return _default
  **/
  @ApiModelProperty(value = "If this ref represents the default artifact repository, rather than a config map.")
  public Boolean isDefault() {
    return _default;
  }

  public void setDefault(Boolean _default) {
    this._default = _default;
  }

  public IoArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus key(String key) {
    this.key = key;
    return this;
  }

   /**
   * The config map key. Defaults to the value of the \&quot;workflows.argoproj.io/default-artifact-repository\&quot; annotation.
   * @return key
  **/
  @ApiModelProperty(value = "The config map key. Defaults to the value of the \"workflows.argoproj.io/default-artifact-repository\" annotation.")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public IoArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus namespace(String namespace) {
    this.namespace = namespace;
    return this;
  }

   /**
   * The namespace of the config map. Defaults to the workflow&#39;s namespace, or the controller&#39;s namespace (if found).
   * @return namespace
  **/
  @ApiModelProperty(value = "The namespace of the config map. Defaults to the workflow's namespace, or the controller's namespace (if found).")
  public String getNamespace() {
    return namespace;
  }

  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus ioArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus = (IoArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus) o;
    return Objects.equals(this.artifactRepository, ioArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus.artifactRepository) &&
        Objects.equals(this.configMap, ioArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus.configMap) &&
        Objects.equals(this._default, ioArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus._default) &&
        Objects.equals(this.key, ioArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus.key) &&
        Objects.equals(this.namespace, ioArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus.namespace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifactRepository, configMap, _default, key, namespace);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1ArtifactRepositoryRefStatus {\n");
    
    sb.append("    artifactRepository: ").append(toIndentedString(artifactRepository)).append("\n");
    sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

