/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.oferto.argo.client.model.IoK8sApiCoreV1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;

/**
 * S3EncryptionOptions used to determine encryption options during s3 operations
 */
@ApiModel(description = "S3EncryptionOptions used to determine encryption options during s3 operations")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojWorkflowV1alpha1S3EncryptionOptions {
  @SerializedName("enableEncryption")
  private Boolean enableEncryption = null;

  @SerializedName("kmsEncryptionContext")
  private String kmsEncryptionContext = null;

  @SerializedName("kmsKeyId")
  private String kmsKeyId = null;

  @SerializedName("serverSideCustomerKeySecret")
  private IoK8sApiCoreV1SecretKeySelector serverSideCustomerKeySecret = null;

  public IoArgoprojWorkflowV1alpha1S3EncryptionOptions enableEncryption(Boolean enableEncryption) {
    this.enableEncryption = enableEncryption;
    return this;
  }

   /**
   * EnableEncryption tells the driver to encrypt objects if set to true. If kmsKeyId and serverSideCustomerKeySecret are not set, SSE-S3 will be used
   * @return enableEncryption
  **/
  @ApiModelProperty(value = "EnableEncryption tells the driver to encrypt objects if set to true. If kmsKeyId and serverSideCustomerKeySecret are not set, SSE-S3 will be used")
  public Boolean isEnableEncryption() {
    return enableEncryption;
  }

  public void setEnableEncryption(Boolean enableEncryption) {
    this.enableEncryption = enableEncryption;
  }

  public IoArgoprojWorkflowV1alpha1S3EncryptionOptions kmsEncryptionContext(String kmsEncryptionContext) {
    this.kmsEncryptionContext = kmsEncryptionContext;
    return this;
  }

   /**
   * KmsEncryptionContext is a json blob that contains an encryption context. See https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#encrypt_context for more information
   * @return kmsEncryptionContext
  **/
  @ApiModelProperty(value = "KmsEncryptionContext is a json blob that contains an encryption context. See https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#encrypt_context for more information")
  public String getKmsEncryptionContext() {
    return kmsEncryptionContext;
  }

  public void setKmsEncryptionContext(String kmsEncryptionContext) {
    this.kmsEncryptionContext = kmsEncryptionContext;
  }

  public IoArgoprojWorkflowV1alpha1S3EncryptionOptions kmsKeyId(String kmsKeyId) {
    this.kmsKeyId = kmsKeyId;
    return this;
  }

   /**
   * KMSKeyId tells the driver to encrypt the object using the specified KMS Key.
   * @return kmsKeyId
  **/
  @ApiModelProperty(value = "KMSKeyId tells the driver to encrypt the object using the specified KMS Key.")
  public String getKmsKeyId() {
    return kmsKeyId;
  }

  public void setKmsKeyId(String kmsKeyId) {
    this.kmsKeyId = kmsKeyId;
  }

  public IoArgoprojWorkflowV1alpha1S3EncryptionOptions serverSideCustomerKeySecret(IoK8sApiCoreV1SecretKeySelector serverSideCustomerKeySecret) {
    this.serverSideCustomerKeySecret = serverSideCustomerKeySecret;
    return this;
  }

   /**
   * ServerSideCustomerKeySecret tells the driver to encrypt the output artifacts using SSE-C with the specified secret.
   * @return serverSideCustomerKeySecret
  **/
  @ApiModelProperty(value = "ServerSideCustomerKeySecret tells the driver to encrypt the output artifacts using SSE-C with the specified secret.")
  public IoK8sApiCoreV1SecretKeySelector getServerSideCustomerKeySecret() {
    return serverSideCustomerKeySecret;
  }

  public void setServerSideCustomerKeySecret(IoK8sApiCoreV1SecretKeySelector serverSideCustomerKeySecret) {
    this.serverSideCustomerKeySecret = serverSideCustomerKeySecret;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1S3EncryptionOptions ioArgoprojWorkflowV1alpha1S3EncryptionOptions = (IoArgoprojWorkflowV1alpha1S3EncryptionOptions) o;
    return Objects.equals(this.enableEncryption, ioArgoprojWorkflowV1alpha1S3EncryptionOptions.enableEncryption) &&
        Objects.equals(this.kmsEncryptionContext, ioArgoprojWorkflowV1alpha1S3EncryptionOptions.kmsEncryptionContext) &&
        Objects.equals(this.kmsKeyId, ioArgoprojWorkflowV1alpha1S3EncryptionOptions.kmsKeyId) &&
        Objects.equals(this.serverSideCustomerKeySecret, ioArgoprojWorkflowV1alpha1S3EncryptionOptions.serverSideCustomerKeySecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enableEncryption, kmsEncryptionContext, kmsKeyId, serverSideCustomerKeySecret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1S3EncryptionOptions {\n");
    
    sb.append("    enableEncryption: ").append(toIndentedString(enableEncryption)).append("\n");
    sb.append("    kmsEncryptionContext: ").append(toIndentedString(kmsEncryptionContext)).append("\n");
    sb.append("    kmsKeyId: ").append(toIndentedString(kmsKeyId)).append("\n");
    sb.append("    serverSideCustomerKeySecret: ").append(toIndentedString(serverSideCustomerKeySecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

