/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.oferto.argo.client.model.IoK8sApiCoreV1ContainerPort;
import io.oferto.argo.client.model.IoK8sApiCoreV1EnvFromSource;
import io.oferto.argo.client.model.IoK8sApiCoreV1EnvVar;
import io.oferto.argo.client.model.IoK8sApiCoreV1Lifecycle;
import io.oferto.argo.client.model.IoK8sApiCoreV1Probe;
import io.oferto.argo.client.model.IoK8sApiCoreV1ResourceRequirements;
import io.oferto.argo.client.model.IoK8sApiCoreV1SecurityContext;
import io.oferto.argo.client.model.IoK8sApiCoreV1VolumeDevice;
import io.oferto.argo.client.model.IoK8sApiCoreV1VolumeMount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UserContainer is a container specified by a user.
 */
@ApiModel(description = "UserContainer is a container specified by a user.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoArgoprojWorkflowV1alpha1UserContainer {
  @SerializedName("args")
  private List<String> args = null;

  @SerializedName("command")
  private List<String> command = null;

  @SerializedName("env")
  private List<IoK8sApiCoreV1EnvVar> env = null;

  @SerializedName("envFrom")
  private List<IoK8sApiCoreV1EnvFromSource> envFrom = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("imagePullPolicy")
  private String imagePullPolicy = null;

  @SerializedName("lifecycle")
  private IoK8sApiCoreV1Lifecycle lifecycle = null;

  @SerializedName("livenessProbe")
  private IoK8sApiCoreV1Probe livenessProbe = null;

  @SerializedName("mirrorVolumeMounts")
  private Boolean mirrorVolumeMounts = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("ports")
  private List<IoK8sApiCoreV1ContainerPort> ports = null;

  @SerializedName("readinessProbe")
  private IoK8sApiCoreV1Probe readinessProbe = null;

  @SerializedName("resources")
  private IoK8sApiCoreV1ResourceRequirements resources = null;

  @SerializedName("securityContext")
  private IoK8sApiCoreV1SecurityContext securityContext = null;

  @SerializedName("startupProbe")
  private IoK8sApiCoreV1Probe startupProbe = null;

  @SerializedName("stdin")
  private Boolean stdin = null;

  @SerializedName("stdinOnce")
  private Boolean stdinOnce = null;

  @SerializedName("terminationMessagePath")
  private String terminationMessagePath = null;

  @SerializedName("terminationMessagePolicy")
  private String terminationMessagePolicy = null;

  @SerializedName("tty")
  private Boolean tty = null;

  @SerializedName("volumeDevices")
  private List<IoK8sApiCoreV1VolumeDevice> volumeDevices = null;

  @SerializedName("volumeMounts")
  private List<IoK8sApiCoreV1VolumeMount> volumeMounts = null;

  @SerializedName("workingDir")
  private String workingDir = null;

  public IoArgoprojWorkflowV1alpha1UserContainer args(List<String> args) {
    this.args = args;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer addArgsItem(String argsItem) {
    if (this.args == null) {
      this.args = new ArrayList<String>();
    }
    this.args.add(argsItem);
    return this;
  }

   /**
   * Arguments to the entrypoint. The container image&#39;s CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container&#39;s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \&quot;$$(VAR_NAME)\&quot; will produce the string literal \&quot;$(VAR_NAME)\&quot;. Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
   * @return args
  **/
  @ApiModelProperty(value = "Arguments to the entrypoint. The container image's CMD is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell")
  public List<String> getArgs() {
    return args;
  }

  public void setArgs(List<String> args) {
    this.args = args;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer command(List<String> command) {
    this.command = command;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer addCommandItem(String commandItem) {
    if (this.command == null) {
      this.command = new ArrayList<String>();
    }
    this.command.add(commandItem);
    return this;
  }

   /**
   * Entrypoint array. Not executed within a shell. The container image&#39;s ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container&#39;s environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \&quot;$$(VAR_NAME)\&quot; will produce the string literal \&quot;$(VAR_NAME)\&quot;. Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
   * @return command
  **/
  @ApiModelProperty(value = "Entrypoint array. Not executed within a shell. The container image's ENTRYPOINT is used if this is not provided. Variable references $(VAR_NAME) are expanded using the container's environment. If a variable cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. \"$$(VAR_NAME)\" will produce the string literal \"$(VAR_NAME)\". Escaped references will never be expanded, regardless of whether the variable exists or not. Cannot be updated. More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell")
  public List<String> getCommand() {
    return command;
  }

  public void setCommand(List<String> command) {
    this.command = command;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer env(List<IoK8sApiCoreV1EnvVar> env) {
    this.env = env;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer addEnvItem(IoK8sApiCoreV1EnvVar envItem) {
    if (this.env == null) {
      this.env = new ArrayList<IoK8sApiCoreV1EnvVar>();
    }
    this.env.add(envItem);
    return this;
  }

   /**
   * List of environment variables to set in the container. Cannot be updated.
   * @return env
  **/
  @ApiModelProperty(value = "List of environment variables to set in the container. Cannot be updated.")
  public List<IoK8sApiCoreV1EnvVar> getEnv() {
    return env;
  }

  public void setEnv(List<IoK8sApiCoreV1EnvVar> env) {
    this.env = env;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer envFrom(List<IoK8sApiCoreV1EnvFromSource> envFrom) {
    this.envFrom = envFrom;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer addEnvFromItem(IoK8sApiCoreV1EnvFromSource envFromItem) {
    if (this.envFrom == null) {
      this.envFrom = new ArrayList<IoK8sApiCoreV1EnvFromSource>();
    }
    this.envFrom.add(envFromItem);
    return this;
  }

   /**
   * List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.
   * @return envFrom
  **/
  @ApiModelProperty(value = "List of sources to populate environment variables in the container. The keys defined within a source must be a C_IDENTIFIER. All invalid keys will be reported as an event when the container is starting. When a key exists in multiple sources, the value associated with the last source will take precedence. Values defined by an Env with a duplicate key will take precedence. Cannot be updated.")
  public List<IoK8sApiCoreV1EnvFromSource> getEnvFrom() {
    return envFrom;
  }

  public void setEnvFrom(List<IoK8sApiCoreV1EnvFromSource> envFrom) {
    this.envFrom = envFrom;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Container image name. More info: https://kubernetes.io/docs/concepts/containers/images This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets.
   * @return image
  **/
  @ApiModelProperty(value = "Container image name. More info: https://kubernetes.io/docs/concepts/containers/images This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets.")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer imagePullPolicy(String imagePullPolicy) {
    this.imagePullPolicy = imagePullPolicy;
    return this;
  }

   /**
   * Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images
   * @return imagePullPolicy
  **/
  @ApiModelProperty(value = "Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images")
  public String getImagePullPolicy() {
    return imagePullPolicy;
  }

  public void setImagePullPolicy(String imagePullPolicy) {
    this.imagePullPolicy = imagePullPolicy;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer lifecycle(IoK8sApiCoreV1Lifecycle lifecycle) {
    this.lifecycle = lifecycle;
    return this;
  }

   /**
   * Actions that the management system should take in response to container lifecycle events. Cannot be updated.
   * @return lifecycle
  **/
  @ApiModelProperty(value = "Actions that the management system should take in response to container lifecycle events. Cannot be updated.")
  public IoK8sApiCoreV1Lifecycle getLifecycle() {
    return lifecycle;
  }

  public void setLifecycle(IoK8sApiCoreV1Lifecycle lifecycle) {
    this.lifecycle = lifecycle;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer livenessProbe(IoK8sApiCoreV1Probe livenessProbe) {
    this.livenessProbe = livenessProbe;
    return this;
  }

   /**
   * Periodic probe of container liveness. Container will be restarted if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
   * @return livenessProbe
  **/
  @ApiModelProperty(value = "Periodic probe of container liveness. Container will be restarted if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes")
  public IoK8sApiCoreV1Probe getLivenessProbe() {
    return livenessProbe;
  }

  public void setLivenessProbe(IoK8sApiCoreV1Probe livenessProbe) {
    this.livenessProbe = livenessProbe;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer mirrorVolumeMounts(Boolean mirrorVolumeMounts) {
    this.mirrorVolumeMounts = mirrorVolumeMounts;
    return this;
  }

   /**
   * MirrorVolumeMounts will mount the same volumes specified in the main container to the container (including artifacts), at the same mountPaths. This enables dind daemon to partially see the same filesystem as the main container in order to use features such as docker volume binding
   * @return mirrorVolumeMounts
  **/
  @ApiModelProperty(value = "MirrorVolumeMounts will mount the same volumes specified in the main container to the container (including artifacts), at the same mountPaths. This enables dind daemon to partially see the same filesystem as the main container in order to use features such as docker volume binding")
  public Boolean isMirrorVolumeMounts() {
    return mirrorVolumeMounts;
  }

  public void setMirrorVolumeMounts(Boolean mirrorVolumeMounts) {
    this.mirrorVolumeMounts = mirrorVolumeMounts;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the container specified as a DNS_LABEL. Each container in a pod must have a unique name (DNS_LABEL). Cannot be updated.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer ports(List<IoK8sApiCoreV1ContainerPort> ports) {
    this.ports = ports;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer addPortsItem(IoK8sApiCoreV1ContainerPort portsItem) {
    if (this.ports == null) {
      this.ports = new ArrayList<IoK8sApiCoreV1ContainerPort>();
    }
    this.ports.add(portsItem);
    return this;
  }

   /**
   * List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default \&quot;0.0.0.0\&quot; address inside a container will be accessible from the network. Cannot be updated.
   * @return ports
  **/
  @ApiModelProperty(value = "List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default \"0.0.0.0\" address inside a container will be accessible from the network. Cannot be updated.")
  public List<IoK8sApiCoreV1ContainerPort> getPorts() {
    return ports;
  }

  public void setPorts(List<IoK8sApiCoreV1ContainerPort> ports) {
    this.ports = ports;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer readinessProbe(IoK8sApiCoreV1Probe readinessProbe) {
    this.readinessProbe = readinessProbe;
    return this;
  }

   /**
   * Periodic probe of container service readiness. Container will be removed from service endpoints if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
   * @return readinessProbe
  **/
  @ApiModelProperty(value = "Periodic probe of container service readiness. Container will be removed from service endpoints if the probe fails. Cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes")
  public IoK8sApiCoreV1Probe getReadinessProbe() {
    return readinessProbe;
  }

  public void setReadinessProbe(IoK8sApiCoreV1Probe readinessProbe) {
    this.readinessProbe = readinessProbe;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer resources(IoK8sApiCoreV1ResourceRequirements resources) {
    this.resources = resources;
    return this;
  }

   /**
   * Compute Resources required by this container. Cannot be updated. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
   * @return resources
  **/
  @ApiModelProperty(value = "Compute Resources required by this container. Cannot be updated. More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/")
  public IoK8sApiCoreV1ResourceRequirements getResources() {
    return resources;
  }

  public void setResources(IoK8sApiCoreV1ResourceRequirements resources) {
    this.resources = resources;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer securityContext(IoK8sApiCoreV1SecurityContext securityContext) {
    this.securityContext = securityContext;
    return this;
  }

   /**
   * SecurityContext defines the security options the container should be run with. If set, the fields of SecurityContext override the equivalent fields of PodSecurityContext. More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
   * @return securityContext
  **/
  @ApiModelProperty(value = "SecurityContext defines the security options the container should be run with. If set, the fields of SecurityContext override the equivalent fields of PodSecurityContext. More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/")
  public IoK8sApiCoreV1SecurityContext getSecurityContext() {
    return securityContext;
  }

  public void setSecurityContext(IoK8sApiCoreV1SecurityContext securityContext) {
    this.securityContext = securityContext;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer startupProbe(IoK8sApiCoreV1Probe startupProbe) {
    this.startupProbe = startupProbe;
    return this;
  }

   /**
   * StartupProbe indicates that the Pod has successfully initialized. If specified, no other probes are executed until this completes successfully. If this probe fails, the Pod will be restarted, just as if the livenessProbe failed. This can be used to provide different probe parameters at the beginning of a Pod&#39;s lifecycle, when it might take a long time to load data or warm a cache, than during steady-state operation. This cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
   * @return startupProbe
  **/
  @ApiModelProperty(value = "StartupProbe indicates that the Pod has successfully initialized. If specified, no other probes are executed until this completes successfully. If this probe fails, the Pod will be restarted, just as if the livenessProbe failed. This can be used to provide different probe parameters at the beginning of a Pod's lifecycle, when it might take a long time to load data or warm a cache, than during steady-state operation. This cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes")
  public IoK8sApiCoreV1Probe getStartupProbe() {
    return startupProbe;
  }

  public void setStartupProbe(IoK8sApiCoreV1Probe startupProbe) {
    this.startupProbe = startupProbe;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer stdin(Boolean stdin) {
    this.stdin = stdin;
    return this;
  }

   /**
   * Whether this container should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the container will always result in EOF. Default is false.
   * @return stdin
  **/
  @ApiModelProperty(value = "Whether this container should allocate a buffer for stdin in the container runtime. If this is not set, reads from stdin in the container will always result in EOF. Default is false.")
  public Boolean isStdin() {
    return stdin;
  }

  public void setStdin(Boolean stdin) {
    this.stdin = stdin;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer stdinOnce(Boolean stdinOnce) {
    this.stdinOnce = stdinOnce;
    return this;
  }

   /**
   * Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the container is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false
   * @return stdinOnce
  **/
  @ApiModelProperty(value = "Whether the container runtime should close the stdin channel after it has been opened by a single attach. When stdin is true the stdin stream will remain open across multiple attach sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the first client attaches to stdin, and then remains open and accepts data until the client disconnects, at which time stdin is closed and remains closed until the container is restarted. If this flag is false, a container processes that reads from stdin will never receive an EOF. Default is false")
  public Boolean isStdinOnce() {
    return stdinOnce;
  }

  public void setStdinOnce(Boolean stdinOnce) {
    this.stdinOnce = stdinOnce;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer terminationMessagePath(String terminationMessagePath) {
    this.terminationMessagePath = terminationMessagePath;
    return this;
  }

   /**
   * Optional: Path at which the file to which the container&#39;s termination message will be written is mounted into the container&#39;s filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated.
   * @return terminationMessagePath
  **/
  @ApiModelProperty(value = "Optional: Path at which the file to which the container's termination message will be written is mounted into the container's filesystem. Message written is intended to be brief final status, such as an assertion failure message. Will be truncated by the node if greater than 4096 bytes. The total message length across all containers will be limited to 12kb. Defaults to /dev/termination-log. Cannot be updated.")
  public String getTerminationMessagePath() {
    return terminationMessagePath;
  }

  public void setTerminationMessagePath(String terminationMessagePath) {
    this.terminationMessagePath = terminationMessagePath;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer terminationMessagePolicy(String terminationMessagePolicy) {
    this.terminationMessagePolicy = terminationMessagePolicy;
    return this;
  }

   /**
   * Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated.
   * @return terminationMessagePolicy
  **/
  @ApiModelProperty(value = "Indicate how the termination message should be populated. File will use the contents of terminationMessagePath to populate the container status message on both success and failure. FallbackToLogsOnError will use the last chunk of container log output if the termination message file is empty and the container exited with an error. The log output is limited to 2048 bytes or 80 lines, whichever is smaller. Defaults to File. Cannot be updated.")
  public String getTerminationMessagePolicy() {
    return terminationMessagePolicy;
  }

  public void setTerminationMessagePolicy(String terminationMessagePolicy) {
    this.terminationMessagePolicy = terminationMessagePolicy;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer tty(Boolean tty) {
    this.tty = tty;
    return this;
  }

   /**
   * Whether this container should allocate a TTY for itself, also requires &#39;stdin&#39; to be true. Default is false.
   * @return tty
  **/
  @ApiModelProperty(value = "Whether this container should allocate a TTY for itself, also requires 'stdin' to be true. Default is false.")
  public Boolean isTty() {
    return tty;
  }

  public void setTty(Boolean tty) {
    this.tty = tty;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer volumeDevices(List<IoK8sApiCoreV1VolumeDevice> volumeDevices) {
    this.volumeDevices = volumeDevices;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer addVolumeDevicesItem(IoK8sApiCoreV1VolumeDevice volumeDevicesItem) {
    if (this.volumeDevices == null) {
      this.volumeDevices = new ArrayList<IoK8sApiCoreV1VolumeDevice>();
    }
    this.volumeDevices.add(volumeDevicesItem);
    return this;
  }

   /**
   * volumeDevices is the list of block devices to be used by the container.
   * @return volumeDevices
  **/
  @ApiModelProperty(value = "volumeDevices is the list of block devices to be used by the container.")
  public List<IoK8sApiCoreV1VolumeDevice> getVolumeDevices() {
    return volumeDevices;
  }

  public void setVolumeDevices(List<IoK8sApiCoreV1VolumeDevice> volumeDevices) {
    this.volumeDevices = volumeDevices;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer volumeMounts(List<IoK8sApiCoreV1VolumeMount> volumeMounts) {
    this.volumeMounts = volumeMounts;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer addVolumeMountsItem(IoK8sApiCoreV1VolumeMount volumeMountsItem) {
    if (this.volumeMounts == null) {
      this.volumeMounts = new ArrayList<IoK8sApiCoreV1VolumeMount>();
    }
    this.volumeMounts.add(volumeMountsItem);
    return this;
  }

   /**
   * Pod volumes to mount into the container&#39;s filesystem. Cannot be updated.
   * @return volumeMounts
  **/
  @ApiModelProperty(value = "Pod volumes to mount into the container's filesystem. Cannot be updated.")
  public List<IoK8sApiCoreV1VolumeMount> getVolumeMounts() {
    return volumeMounts;
  }

  public void setVolumeMounts(List<IoK8sApiCoreV1VolumeMount> volumeMounts) {
    this.volumeMounts = volumeMounts;
  }

  public IoArgoprojWorkflowV1alpha1UserContainer workingDir(String workingDir) {
    this.workingDir = workingDir;
    return this;
  }

   /**
   * Container&#39;s working directory. If not specified, the container runtime&#39;s default will be used, which might be configured in the container image. Cannot be updated.
   * @return workingDir
  **/
  @ApiModelProperty(value = "Container's working directory. If not specified, the container runtime's default will be used, which might be configured in the container image. Cannot be updated.")
  public String getWorkingDir() {
    return workingDir;
  }

  public void setWorkingDir(String workingDir) {
    this.workingDir = workingDir;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1UserContainer ioArgoprojWorkflowV1alpha1UserContainer = (IoArgoprojWorkflowV1alpha1UserContainer) o;
    return Objects.equals(this.args, ioArgoprojWorkflowV1alpha1UserContainer.args) &&
        Objects.equals(this.command, ioArgoprojWorkflowV1alpha1UserContainer.command) &&
        Objects.equals(this.env, ioArgoprojWorkflowV1alpha1UserContainer.env) &&
        Objects.equals(this.envFrom, ioArgoprojWorkflowV1alpha1UserContainer.envFrom) &&
        Objects.equals(this.image, ioArgoprojWorkflowV1alpha1UserContainer.image) &&
        Objects.equals(this.imagePullPolicy, ioArgoprojWorkflowV1alpha1UserContainer.imagePullPolicy) &&
        Objects.equals(this.lifecycle, ioArgoprojWorkflowV1alpha1UserContainer.lifecycle) &&
        Objects.equals(this.livenessProbe, ioArgoprojWorkflowV1alpha1UserContainer.livenessProbe) &&
        Objects.equals(this.mirrorVolumeMounts, ioArgoprojWorkflowV1alpha1UserContainer.mirrorVolumeMounts) &&
        Objects.equals(this.name, ioArgoprojWorkflowV1alpha1UserContainer.name) &&
        Objects.equals(this.ports, ioArgoprojWorkflowV1alpha1UserContainer.ports) &&
        Objects.equals(this.readinessProbe, ioArgoprojWorkflowV1alpha1UserContainer.readinessProbe) &&
        Objects.equals(this.resources, ioArgoprojWorkflowV1alpha1UserContainer.resources) &&
        Objects.equals(this.securityContext, ioArgoprojWorkflowV1alpha1UserContainer.securityContext) &&
        Objects.equals(this.startupProbe, ioArgoprojWorkflowV1alpha1UserContainer.startupProbe) &&
        Objects.equals(this.stdin, ioArgoprojWorkflowV1alpha1UserContainer.stdin) &&
        Objects.equals(this.stdinOnce, ioArgoprojWorkflowV1alpha1UserContainer.stdinOnce) &&
        Objects.equals(this.terminationMessagePath, ioArgoprojWorkflowV1alpha1UserContainer.terminationMessagePath) &&
        Objects.equals(this.terminationMessagePolicy, ioArgoprojWorkflowV1alpha1UserContainer.terminationMessagePolicy) &&
        Objects.equals(this.tty, ioArgoprojWorkflowV1alpha1UserContainer.tty) &&
        Objects.equals(this.volumeDevices, ioArgoprojWorkflowV1alpha1UserContainer.volumeDevices) &&
        Objects.equals(this.volumeMounts, ioArgoprojWorkflowV1alpha1UserContainer.volumeMounts) &&
        Objects.equals(this.workingDir, ioArgoprojWorkflowV1alpha1UserContainer.workingDir);
  }

  @Override
  public int hashCode() {
    return Objects.hash(args, command, env, envFrom, image, imagePullPolicy, lifecycle, livenessProbe, mirrorVolumeMounts, name, ports, readinessProbe, resources, securityContext, startupProbe, stdin, stdinOnce, terminationMessagePath, terminationMessagePolicy, tty, volumeDevices, volumeMounts, workingDir);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1UserContainer {\n");
    
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    command: ").append(toIndentedString(command)).append("\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("    envFrom: ").append(toIndentedString(envFrom)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    imagePullPolicy: ").append(toIndentedString(imagePullPolicy)).append("\n");
    sb.append("    lifecycle: ").append(toIndentedString(lifecycle)).append("\n");
    sb.append("    livenessProbe: ").append(toIndentedString(livenessProbe)).append("\n");
    sb.append("    mirrorVolumeMounts: ").append(toIndentedString(mirrorVolumeMounts)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ports: ").append(toIndentedString(ports)).append("\n");
    sb.append("    readinessProbe: ").append(toIndentedString(readinessProbe)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    securityContext: ").append(toIndentedString(securityContext)).append("\n");
    sb.append("    startupProbe: ").append(toIndentedString(startupProbe)).append("\n");
    sb.append("    stdin: ").append(toIndentedString(stdin)).append("\n");
    sb.append("    stdinOnce: ").append(toIndentedString(stdinOnce)).append("\n");
    sb.append("    terminationMessagePath: ").append(toIndentedString(terminationMessagePath)).append("\n");
    sb.append("    terminationMessagePolicy: ").append(toIndentedString(terminationMessagePolicy)).append("\n");
    sb.append("    tty: ").append(toIndentedString(tty)).append("\n");
    sb.append("    volumeDevices: ").append(toIndentedString(volumeDevices)).append("\n");
    sb.append("    volumeMounts: ").append(toIndentedString(volumeMounts)).append("\n");
    sb.append("    workingDir: ").append(toIndentedString(workingDir)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

