/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/
 *
 * OpenAPI spec version: VERSION
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.oferto.argo.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.oferto.argo.client.model.IoK8sApiCoreV1ConfigMapEnvSource;
import io.oferto.argo.client.model.IoK8sApiCoreV1SecretEnvSource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;

/**
 * EnvFromSource represents the source of a set of ConfigMaps
 */
@ApiModel(description = "EnvFromSource represents the source of a set of ConfigMaps")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-03-17T20:59:50.224Z")
public class IoK8sApiCoreV1EnvFromSource {
  @SerializedName("configMapRef")
  private IoK8sApiCoreV1ConfigMapEnvSource configMapRef = null;

  @SerializedName("prefix")
  private String prefix = null;

  @SerializedName("secretRef")
  private IoK8sApiCoreV1SecretEnvSource secretRef = null;

  public IoK8sApiCoreV1EnvFromSource configMapRef(IoK8sApiCoreV1ConfigMapEnvSource configMapRef) {
    this.configMapRef = configMapRef;
    return this;
  }

   /**
   * The ConfigMap to select from
   * @return configMapRef
  **/
  @ApiModelProperty(value = "The ConfigMap to select from")
  public IoK8sApiCoreV1ConfigMapEnvSource getConfigMapRef() {
    return configMapRef;
  }

  public void setConfigMapRef(IoK8sApiCoreV1ConfigMapEnvSource configMapRef) {
    this.configMapRef = configMapRef;
  }

  public IoK8sApiCoreV1EnvFromSource prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER.
   * @return prefix
  **/
  @ApiModelProperty(value = "An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER.")
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }

  public IoK8sApiCoreV1EnvFromSource secretRef(IoK8sApiCoreV1SecretEnvSource secretRef) {
    this.secretRef = secretRef;
    return this;
  }

   /**
   * The Secret to select from
   * @return secretRef
  **/
  @ApiModelProperty(value = "The Secret to select from")
  public IoK8sApiCoreV1SecretEnvSource getSecretRef() {
    return secretRef;
  }

  public void setSecretRef(IoK8sApiCoreV1SecretEnvSource secretRef) {
    this.secretRef = secretRef;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoK8sApiCoreV1EnvFromSource ioK8sApiCoreV1EnvFromSource = (IoK8sApiCoreV1EnvFromSource) o;
    return Objects.equals(this.configMapRef, ioK8sApiCoreV1EnvFromSource.configMapRef) &&
        Objects.equals(this.prefix, ioK8sApiCoreV1EnvFromSource.prefix) &&
        Objects.equals(this.secretRef, ioK8sApiCoreV1EnvFromSource.secretRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configMapRef, prefix, secretRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoK8sApiCoreV1EnvFromSource {\n");
    
    sb.append("    configMapRef: ").append(toIndentedString(configMapRef)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    secretRef: ").append(toIndentedString(secretRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

